//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trust.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        internal object ITEM_NAME;

        public int COMPANY_ID { get; set; }
        public string COMPANY_NAME { get; set; }
        public string COMPANY_CITY { get; set; }
    
        public virtual food food { get; set; }
    }
}
