//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trust.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class food
    {
        public string ITEM_NAME { get; set; }
        public int COMPANY_ID { get; set; }
    
        public virtual company company { get; set; }
    }
}
