//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTutorial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table1
    {
        public Nullable<int> ApartmentID { get; set; }
        public string ApartmentName { get; set; }
        public Nullable<int> TotalCount { get; set; }
        public int FloorID { get; set; }
    }
}
