//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayEleven.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lovsan
    {
        public int EmpID { get; set; }
        public string EmpName { get; set; }
        public int DepartmentID { get; set; }
        public string Address { get; set; }
    
        public virtual lovsan2 lovsan2 { get; set; }
    }
}
