//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Measurement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENT1
    {
        public int DEPTNO { get; set; }
        public string DNAME { get; set; }
        public string LOCATION { get; set; }
    }
}
