//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> Phoneno { get; set; }
        public int MobileID { get; set; }
    
        public virtual detail detail { get; set; }
    }
}
